### ISSUE TITLE
Ensure consistent and cohesive styling across application

### ISSUE THREAD

**Issue by skydonline** [DSC-McMaster-U/Gamified-Learning-Platform#101]
There are some parts of the application that don't look like they belong to one central theme. Update the view to match it according to the [lessons mockup design](https://github.com/DSC-McMaster-U/Gamified-Learning-Platform/blob/main/design/Gamified_Learning_Lesson_Mockup.png). Notice the simplicity, use of specific color codes, and font sizes. There are inconsistencies across all pages of the website.

**Comment by zareentk** [comment]
Hi @alexchen2 would you be able to work on this ticket?

**Comment by alexchen2** [comment]
Sure, I can take this one
