### ISSUE TITLE
Design and develop front-end code for a static landing page

### ISSUE THREAD

**Issue by alexchen2** [DSC-McMaster-U/Gamified-Learning-Platform#106]
As of now, upon loading the website in its current state, a user will be faced with a barren `index.html` page that does not tell them anything about our product to them, nor provides any easy navigation or access to other parts of the Gamified Learning platform. Needless to say, this doesn't exactly set the best impression on potential new consumers. We need some sort of page to greet users with, inform them what Gamified is, and convince them to use our services.

The task is to design a mockup and create frontend code for a landing page that users would be greeted with, upon visiting the website. The landing page should have an appealing, modern design to attract potential consumers while advertising our product and its features, yet it should still be in line with the design from our other pages. 

For some inspiration, you can find a couple of landing page examples/templates [here](https://unbounce.com/landing-page-examples/best-landing-page-examples/) and [here](https://www.figma.com/community/file/1127302394641561751/50-landing-page-designs?searchSessionId=lsi3oza5-lisq8usiqi).

**Comment by zareentk** [comment]
Hi @racheldennis can you take this ticket?
