### ISSUE TITLE
Create a Contact Us/Help Page

### ISSUE THREAD

**Issue by racheldennis** [DSC-McMaster-U/Gamified-Learning-Platform#109]
Create a help page to allow users to contact administration if errors occur or issues arise, such as forgetting passwords or not having access to email.

Examples include:

- Include a form to fill out about a concern
- create a FAQ on common questions users may ask

**Comment by skydonline** [comment]
Interested

**Comment by zareentk** [comment]
Although helpful, not top priority so will be closing
