### ISSUE TITLE
Design mock-up for dashboard page

### ISSUE THREAD

**Issue by zareentk** [DSC-McMaster-U/Gamified-Learning-Platform#31]
Design the structure of the page using the theme from the registration and login pages.
Here’s some additional notes:
- Integrate in User Profile
- Progress/Streak checker (graphic component)
- Point Systems
- Badge sections/Accomplishments
- Lessons and one for quizzes
- Structure of the dashboard
- Look at codesignal’s UI
- Look at Duolingo’s UI

**Comment by MithunPara** [comment]
interested
