### ISSUE TITLE
Implement logic to fetch updates and data from the backend to the display on the dashboard

### ISSUE THREAD

**Issue by zareentk** [DSC-McMaster-U/Gamified-Learning-Platform#44]
So a big section of this code is being able to update the frontend of the dashboard application when new updates are added such as updating the number of points or the number of logins that a user had (streak). AJAX is a good way to pass information from the backend to directly update the frontend. Some information of doing this can be seen here:
https://flask.palletsprojects.com/en/2.0.x/patterns/jquery/
https://towardsdatascience.com/using-python-flask-and-ajax-to-pass-information-between-the-client-and-server-90670c64d688

**Comment by skydonline** [comment]
Interested
