### ISSUE TITLE
Implement backend login authetication logic

### ISSUE THREAD

**Issue by zareentk** [DSC-McMaster-U/Gamified-Learning-Platform#5]
Implement logic for Login functionalities. Consider using Flask extensions/libraries for added security.
https://realpython.com/using-flask-login-for-user-management-with-flask/#:~:text=Flask%2Dlogin%20is%20a%20Flask,and%20a%20few%20simple%20functions.

**Comment by skydonline** [comment]
Interested

**Comment by MithunPara** [comment]
Would be interested in working on this issue

**Comment by racheldennis** [comment]
Interested

**Comment by alexchen2** [comment]
Interested in working on this one

**Comment by cenesdeveloper** [comment]
Interested

**Comment by racheldennis** [comment]
interested

**Comment by skydonline** [comment]
Completed this issue. The user authentication logic is located in auth.py.
