### ISSUE TITLE
Setup frontend for quiz page

### ISSUE THREAD

**Issue by zareentk** [DSC-McMaster-U/Gamified-Learning-Platform#51]
Develop the frontend for the quiz page, with the current structure being all quiz questions and multiple choice options displayed on a single page. In the future when we have time we will structure it to be more dynamic and have a next button that will display questions on single pages. Follow the mockup structured previously

**Comment by racheldennis** [comment]
Interested

**Comment by skydonline** [comment]
Interested

**Comment by clarawong20** [comment]
Interested
