### ISSUE TITLE
Implement User Registration Logic

### ISSUE THREAD

**Issue by zareentk** [DSC-McMaster-U/Gamified-Learning-Platform#6]
Create backend functionality allowing users to register, hashing passwords for security.
https://realpython.com/using-flask-login-for-user-management-with-flask/#:~:text=Flask%2Dlogin%20is%20a%20Flask,and%20a%20few%20simple%20functions.

**Comment by cenesdeveloper** [comment]
I am interested in solving this issue

**Comment by skydonline** [comment]
Interested

**Comment by MithunPara** [comment]
Would be interested in working on this issue

**Comment by alexchen2** [comment]
Interested in working on this one.
