### ISSUE TITLE
 Design and Implement Database Schema for Leaderboard

### ISSUE THREAD

**Issue by zareentk** [DSC-McMaster-U/Gamified-Learning-Platform#78]
Create a schema to store user points and rankings. This schema should efficiently support frequent updates and retrievals for the leaderboard. Ensure that the database queries for the leaderboard are optimized for performance, considering the potentially large number of users.

**Comment by skydonline** [comment]
Interested

**Comment by MithunPara** [comment]
interested

**Comment by racheldennis** [comment]
interested
