### ISSUE TITLE
Implement Leaderboard Aggregation Logic

### ISSUE THREAD

**Issue by zareentk** [DSC-McMaster-U/Gamified-Learning-Platform#79]
Develop logic to calculate user rankings based on points. This includes writing using an efficient data structures to sort users by their points. Ensure this logic accounts for ties in points.

**Comment by alexchen2** [comment]
interested

**Comment by cenesdeveloper** [comment]
Interested

**Comment by MithunPara** [comment]
interested

**Comment by EricMBu** [comment]
Interested
