### ISSUE TITLE
Create API Endpoint for Retrieving Leaderboard Data

### ISSUE THREAD

**Issue by zareentk** [DSC-McMaster-U/Gamified-Learning-Platform#80]
- Create a new route in your Flask app (e.g., @app.route('/leaderboard')) that handles GET requests.
- Use the leaderboard logic to fetch and return the sorted list of users.
- Implement pagination in the response to handle a large number of users.

**Comment by racheldennis** [comment]
interested

**Comment by skydonline** [comment]
Interested

**Comment by alexchen2** [comment]
interested

**Comment by clarawong20** [comment]
interested

**Comment by EricMBu** [comment]
Interested
