### ISSUE TITLE
Implement Leaderboard Update Mechanism

### ISSUE THREAD

**Issue by zareentk** [DSC-McMaster-U/Gamified-Learning-Platform#81]
- Develop a mechanism to periodically update the leaderboard on the frontend, either through polling or by using websockets for real-time updates.
- Set up an interval that sends AJAX requests to the leaderboard API endpoint every few minutes.
- Ensure that the frontend handles the incoming data to update the leaderboard without reloading the entire page.
- Implement error handling for failed requests.

**Comment by clarawong20** [comment]
interested
