### ISSUE TITLE
 Implement Leaderboard UI in HTML/CSS

### ISSUE THREAD

**Issue by zareentk** [DSC-McMaster-U/Gamified-Learning-Platform#83]
- Translate the UI mockups into HTML and CSS, ensuring responsiveness and adherence to the overall design theme of the application.
- Using Flask's Jinja2 templates, create the HTML for the leaderboard page.
- Use CSS to style the leaderboard.

**Comment by angadk4** [comment]
interested

**Comment by alexchen2** [comment]
interested
